export const backendData = {
  carData: [
    {
      id: 1,
      type: "Car",
      image: "/images/car1.jpg",
      title: "Sedan",
      brand: "Toyota",
      model: "Camry",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 20000,
      rentPrice: 20,
      registration: "AB123CD",
      pickupDate: "2024-09-25",
      returnDate: "2024-09-28",
      pickupTime: "09:00 AM",
      dropoffTime: "05:00 PM",
      status: "Available",
      description: "A comfortable sedan for city driving.",
      bookingReference: "CAR123456",
      paymentMethod: "Credit Card",
    },
    {
      id: 2,
      type: "Car",
      image: "/images/car2.jpg",
      title: "SUV",
      brand: "Honda",
      model: "CR-V",
      transmission: "Automatic",
      fuelType: "Diesel",
      price: 30000,
      rentPrice: 30,
      registration: "XY456ZT",
      pickupDate: "2024-09-28",
      returnDate: "2024-10-01",
      pickupTime: "08:30 AM",
      dropoffTime: "06:00 PM",
      status: "Not Available",
      description: "A spacious SUV for family trips.",
      bookingReference: "CAR123457",
      paymentMethod: "PayPal",
    },
    {
      id: 3,
      type: "Car",
      image: "/images/car3.jpg",
      title: "Hatchback",
      brand: "Ford",
      model: "Fiesta",
      transmission: "Manual",
      fuelType: "Gasoline",
      price: 15000,
      rentPrice: 15,
      registration: "MN789OP",
      pickupDate: "2024-10-01",
      returnDate: "2024-10-04",
      pickupTime: "10:00 AM",
      dropoffTime: "04:00 PM",
      status: "Available",
      description: "A compact hatchback for easy parking.",
      bookingReference: "CAR123458",
      paymentMethod: "Debit Card",
    },
    {
      id: 4,
      type: "Car",
      image: "/images/car4.jpg",
      title: "Convertible",
      brand: "BMW",
      model: "Z4",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 50000,
      rentPrice: 50,
      registration: "CV789BM",
      pickupDate: "2024-10-05",
      returnDate: "2024-10-08",
      pickupTime: "11:00 AM",
      dropoffTime: "03:00 PM",
      status: "Available",
      description: "A stylish convertible for open-air driving.",
      bookingReference: "CAR123459",
      paymentMethod: "Credit Card",
    },
    {
      id: 5,
      type: "Car",
      image: "/images/car5.jpg",
      title: "Coupe",
      brand: "Mercedes",
      model: "C-Class",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 45000,
      rentPrice: 45,
      registration: "CP234MB",
      pickupDate: "2024-10-06",
      returnDate: "2024-10-09",
      pickupTime: "12:00 PM",
      dropoffTime: "04:00 PM",
      status: "Available",
      description: "A luxury coupe with high performance.",
      bookingReference: "CAR123460",
      paymentMethod: "Debit Card",
    },
    {
      id: 6,
      type: "Car",
      image: "/images/car6.jpg",
      title: "Minivan",
      brand: "Kia",
      model: "Carnival",
      transmission: "Automatic",
      fuelType: "Diesel",
      price: 35000,
      rentPrice: 35,
      registration: "MN567KI",
      pickupDate: "2024-10-10",
      returnDate: "2024-10-13",
      pickupTime: "07:00 AM",
      dropoffTime: "05:30 PM",
      status: "Not Available",
      description: "A family-friendly minivan with ample space.",
      bookingReference: "CAR123461",
      paymentMethod: "Credit Card",
    },
    {
      id: 7,
      type: "Car",
      image: "/images/car7.jpg",
      title: "Luxury",
      brand: "Tesla",
      model: "Model S",
      transmission: "Automatic",
      fuelType: "Electric",
      price: 80000,
      rentPrice: 80,
      registration: "LX789TS",
      pickupDate: "2024-10-14",
      returnDate: "2024-10-17",
      pickupTime: "09:30 AM",
      dropoffTime: "06:00 PM",
      status: "Available",
      description: "A premium electric car with advanced features.",
      bookingReference: "CAR123462",
      paymentMethod: "PayPal",
    },
    {
      id: 8,
      type: "Car",
      image: "/images/car8.jpg",
      title: "Station Wagon",
      brand: "Volvo",
      model: "V60",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 35000,
      rentPrice: 35,
      registration: "SW345VO",
      pickupDate: "2024-10-18",
      returnDate: "2024-10-21",
      pickupTime: "10:00 AM",
      dropoffTime: "05:00 PM",
      status: "Not Available",
      description: "A versatile station wagon with plenty of cargo space.",
      bookingReference: "CAR123463",
      paymentMethod: "Credit Card",
    },
    {
      id: 9,
      type: "Car",
      image: "/images/car9.jpg",
      title: "Pickup Truck",
      brand: "Ford",
      model: "F-150",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 40000,
      rentPrice: 40,
      registration: "PK456FD",
      pickupDate: "2024-10-22",
      returnDate: "2024-10-25",
      pickupTime: "11:00 AM",
      dropoffTime: "06:30 PM",
      status: "Available",
      description: "A powerful pickup truck for tough jobs.",
      bookingReference: "CAR123464",
      paymentMethod: "Debit Card",
    },
    {
      id: 10,
      type: "Car",
      image: "/images/car10.jpg",
      title: "Electric",
      brand: "Nissan",
      model: "Leaf",
      transmission: "Automatic",
      fuelType: "Electric",
      price: 25000,
      rentPrice: 25,
      registration: "EL678NS",
      pickupDate: "2024-10-26",
      returnDate: "2024-10-29",
      pickupTime: "08:00 AM",
      dropoffTime: "04:00 PM",
      status: "Available",
      description: "An eco-friendly electric car with great efficiency.",
      bookingReference: "CAR123465",
      paymentMethod: "Credit Card",
    },
  ],
  bikeData: [
    {
      id: 11,
      type: "Bike",
      image: "/images/bike1.jpg",
      title: "Sport Bike",
      brand: "Yamaha",
      model: "YZF-R3",
      transmission: "Manual",
      fuelType: "Gasoline",
      price: 8000,
      rentPrice: 10,
      registration: "BK123YZ",
      pickupDate: "2024-09-25",
      returnDate: "2024-09-28",
      pickupTime: "09:00 AM",
      dropoffTime: "05:00 PM",
      status: "Available",
      description: "A fast sport bike for thrill-seekers.",
      bookingReference: "BIKE123456",
      paymentMethod: "Credit Card",
    },
    {
      id: 12,
      type: "Bike",
      image: "/images/bike2.jpg",
      title: "Cruiser",
      brand: "Harley Davidson",
      model: "Street 750",
      transmission: "Manual",
      fuelType: "Gasoline",
      price: 12000,
      rentPrice: 12,
      registration: "CR567HD",
      pickupDate: "2024-09-26",
      returnDate: "2024-09-29",
      pickupTime: "10:00 AM",
      dropoffTime: "04:30 PM",
      status: "Not Available",
      description: "A classic cruiser for long rides.",
      bookingReference: "BIKE123457",
      paymentMethod: "PayPal",
    },
    {
      id: 13,
      type: "Bike",
      image: "/images/bike3.jpg",
      title: "Dirt Bike",
      brand: "Kawasaki",
      model: "KX250",
      transmission: "Manual",
      fuelType: "Gasoline",
      price: 10000,
      rentPrice: 11,
      registration: "DR456KW",
      pickupDate: "2024-09-30",
      returnDate: "2024-10-02",
      pickupTime: "07:30 AM",
      dropoffTime: "03:00 PM",
      status: "Available",
      description: "A rugged dirt bike for off-road adventures.",
      bookingReference: "BIKE123458",
      paymentMethod: "Debit Card",
    },
    {
      id: 14,
      type: "Bike",
      image: "/images/bike4.jpg",
      title: "Touring Bike",
      brand: "Honda",
      model: "Gold Wing",
      transmission: "Manual",
      fuelType: "Gasoline",
      price: 25000,
      rentPrice: 20,
      registration: "TR567HD",
      pickupDate: "2024-10-03",
      returnDate: "2024-10-05",
      pickupTime: "08:30 AM",
      dropoffTime: "06:00 PM",
      status: "Not Available",
      description: "A comfortable touring bike for long-distance travel.",
      bookingReference: "BIKE123459",
      paymentMethod: "Credit Card",
    },
    {
      id: 15,
      type: "Bike",
      image: "/images/bike5.jpg",
      title: "Electric Bike",
      brand: "Zero Motorcycles",
      model: "SR/F",
      transmission: "Automatic",
      fuelType: "Electric",
      price: 15000,
      rentPrice: 15,
      registration: "EL345ZR",
      pickupDate: "2024-10-06",
      returnDate: "2024-10-09",
      pickupTime: "09:00 AM",
      dropoffTime: "05:00 PM",
      status: "Available",
      description: "A powerful electric bike with instant torque.",
      bookingReference: "BIKE123460",
      paymentMethod: "Debit Card",
    },
    {
      id: 16,
      type: "Bike",
      image: "/images/bike6.jpg",
      title: "Adventure Bike",
      brand: "BMW",
      model: "GS1200",
      transmission: "Manual",
      fuelType: "Gasoline",
      price: 22000,
      rentPrice: 22,
      registration: "AD678BM",
      pickupDate: "2024-10-10",
      returnDate: "2024-10-13",
      pickupTime: "10:00 AM",
      dropoffTime: "06:30 PM",
      status: "Available",
      description: "A capable adventure bike for any terrain.",
      bookingReference: "BIKE123461",
      paymentMethod: "Credit Card",
    },
    {
      id: 17,
      type: "Bike",
      image: "/images/bike7.jpg",
      title: "Scooter",
      brand: "Vespa",
      model: "Primavera",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 5000,
      rentPrice: 8,
      registration: "SC234VP",
      pickupDate: "2024-10-14",
      returnDate: "2024-10-16",
      pickupTime: "11:00 AM",
      dropoffTime: "04:00 PM",
      status: "Available",
      description: "A stylish scooter for urban commuting.",
      bookingReference: "BIKE123462",
      paymentMethod: "PayPal",
    },
    {
      id: 18,
      type: "Bike",
      image: "/images/bike8.jpg",
      title: "Cafe Racer",
      brand: "Royal Enfield",
      model: "Continental GT",
      transmission: "Manual",
      fuelType: "Gasoline",
      price: 9000,
      rentPrice: 9,
      registration: "CR456RE",
      pickupDate: "2024-10-17",
      returnDate: "2024-10-20",
      pickupTime: "09:30 AM",
      dropoffTime: "03:30 PM",
      status: "Available",
      description: "A retro-styled bike for classic ride enthusiasts.",
      bookingReference: "BIKE123463",
      paymentMethod: "Credit Card",
    },
    {
      id: 19,
      type: "Bike",
      image: "/images/bike9.jpg",
      title: "Standard Bike",
      brand: "Honda",
      model: "CB300R",
      transmission: "Manual",
      fuelType: "Gasoline",
      price: 7000,
      rentPrice: 10,
      registration: "ST789HD",
      pickupDate: "2024-10-21",
      returnDate: "2024-10-23",
      pickupTime: "08:00 AM",
      dropoffTime: "05:00 PM",
      status: "Available",
      description: "A versatile standard bike for everyday use.",
      bookingReference: "BIKE123464",
      paymentMethod: "Debit Card",
    },
    {
      id: 20,
      type: "Bike",
      image: "/images/bike10.jpg",
      title: "Chopper",
      brand: "Indian",
      model: "Scout Bobber",
      transmission: "Manual",
      fuelType: "Gasoline",
      price: 18000,
      rentPrice: 18,
      registration: "CH123ID",
      pickupDate: "2024-10-24",
      returnDate: "2024-10-27",
      pickupTime: "07:00 AM",
      dropoffTime: "06:00 PM",
      status: "Not Available",
      description: "A bold chopper with a distinctive style.",
      bookingReference: "BIKE123465",
      paymentMethod: "Credit Card",
    },
  ],
  sixSeaterData: [
    {
      id: 21,
      type: "6 Seater",
      image: "/images/sixseater1.jpg",
      title: "Van",
      brand: "Toyota",
      model: "Sienna",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 40000,
      rentPrice: 40,
      registration: "SS123TO",
      pickupDate: "2024-09-25",
      returnDate: "2024-09-30",
      pickupTime: "07:30 AM",
      dropoffTime: "06:00 PM",
      status: "Available",
      description: "A spacious van for group travel.",
      bookingReference: "VAN123456",
      paymentMethod: "Debit Card",
    },
    {
      id: 22,
      type: "6 Seater",
      image: "/images/sixseater2.jpg",
      title: "SUV",
      brand: "Chevrolet",
      model: "Suburban",
      transmission: "Automatic",
      fuelType: "Diesel",
      price: 50000,
      rentPrice: 50,
      registration: "SS456CH",
      pickupDate: "2024-09-26",
      returnDate: "2024-10-01",
      pickupTime: "08:00 AM",
      dropoffTime: "07:00 PM",
      status: "Not Available",
      description: "An SUV with extra seating for large groups.",
      bookingReference: "VAN123457",
      paymentMethod: "Credit Card",
    },
    {
      id: 23,
      type: "6 Seater",
      image: "/images/sixseater3.jpg",
      title: "Luxury Van",
      brand: "Mercedes",
      model: "V-Class",
      transmission: "Automatic",
      fuelType: "Diesel",
      price: 60000,
      rentPrice: 60,
      registration: "SS789MB",
      pickupDate: "2024-10-02",
      returnDate: "2024-10-05",
      pickupTime: "09:00 AM",
      dropoffTime: "05:00 PM",
      status: "Available",
      description: "A luxurious van with premium features.",
      bookingReference: "VAN123458",
      paymentMethod: "PayPal",
    },
    {
      id: 24,
      type: "6 Seater",
      image: "/images/sixseater4.jpg",
      title: "Minivan",
      brand: "Chrysler",
      model: "Pacifica",
      transmission: "Automatic",
      fuelType: "Hybrid",
      price: 45000,
      rentPrice: 45,
      registration: "SS345CH",
      pickupDate: "2024-10-06",
      returnDate: "2024-10-09",
      pickupTime: "08:30 AM",
      dropoffTime: "06:00 PM",
      status: "Available",
      description: "A family-friendly minivan with hybrid technology.",
      bookingReference: "VAN123459",
      paymentMethod: "Credit Card",
    },
    {
      id: 25,
      type: "6 Seater",
      image: "/images/sixseater5.jpg",
      title: "Crossover",
      brand: "Mazda",
      model: "CX-9",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 38000,
      rentPrice: 38,
      registration: "SS567MA",
      pickupDate: "2024-10-10",
      returnDate: "2024-10-12",
      pickupTime: "10:00 AM",
      dropoffTime: "05:30 PM",
      status: "Not Available",
      description: "A sleek crossover with extra seating.",
      bookingReference: "VAN123460",
      paymentMethod: "Debit Card",
    },
    {
      id: 26,
      type: "6 Seater",
      image: "/images/sixseater6.jpg",
      title: "Extended SUV",
      brand: "Ford",
      model: "Expedition",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 55000,
      rentPrice: 55,
      registration: "SS678FD",
      pickupDate: "2024-10-13",
      returnDate: "2024-10-16",
      pickupTime: "09:30 AM",
      dropoffTime: "06:00 PM",
      status: "Available",
      description: "An extended SUV with powerful performance.",
      bookingReference: "VAN123461",
      paymentMethod: "Credit Card",
    },
    {
      id: 27,
      type: "6 Seater",
      image: "/images/sixseater7.jpg",
      title: "Family Van",
      brand: "Honda",
      model: "Odyssey",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 42000,
      rentPrice: 42,
      registration: "SS789HD",
      pickupDate: "2024-10-17",
      returnDate: "2024-10-19",
      pickupTime: "10:00 AM",
      dropoffTime: "05:00 PM",
      status: "Available",
      description: "A reliable family van with great safety features.",
      bookingReference: "VAN123462",
      paymentMethod: "PayPal",
    },
    {
      id: 28,
      type: "6 Seater",
      image: "/images/sixseater8.jpg",
      title: "Luxury SUV",
      brand: "Lexus",
      model: "LX 570",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 70000,
      rentPrice: 70,
      registration: "SS345LX",
      pickupDate: "2024-10-20",
      returnDate: "2024-10-23",
      pickupTime: "11:00 AM",
      dropoffTime: "04:00 PM",
      status: "Available",
      description: "A luxury SUV with advanced off-road capabilities.",
      bookingReference: "VAN123463",
      paymentMethod: "Credit Card",
    },
    {
      id: 29,
      type: "6 Seater",
      image: "/images/sixseater9.jpg",
      title: "Hybrid SUV",
      brand: "Toyota",
      model: "Highlander Hybrid",
      transmission: "Automatic",
      fuelType: "Hybrid",
      price: 48000,
      rentPrice: 48,
      registration: "SS567HY",
      pickupDate: "2024-10-24",
      returnDate: "2024-10-27",
      pickupTime: "07:00 AM",
      dropoffTime: "06:00 PM",
      status: "Not Available",
      description: "An eco-friendly hybrid SUV with ample seating.",
      bookingReference: "VAN123464",
      paymentMethod: "Debit Card",
    },
    {
      id: 30,
      type: "6 Seater",
      image: "/images/sixseater10.jpg",
      title: "Extended Minivan",
      brand: "Kia",
      model: "Sedona",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 36000,
      rentPrice: 36,
      registration: "SS678KI",
      pickupDate: "2024-10-28",
      returnDate: "2024-10-31",
      pickupTime: "08:00 AM",
      dropoffTime: "05:30 PM",
      status: "Available",
      description: "An extended minivan with extra cargo space.",
      bookingReference: "VAN123465",
      paymentMethod: "Credit Card",
    },
  ],
};
