export const backendData = {
  carData: [
    {
      id: 1,
      type: "car",
      image: "/images/car1.jpg",
      title: "Sedan",
      brand: "Toyota",
      model: "Camry",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 20000,
      rentPrice: 20,
      registration: "AB123CD",
      pickupDate: "2024-09-25",
      returnDate: "2024-09-30",
      status: "Available",
      description: "A comfortable sedan for city driving.",
    },
    {
      id: 2,
      type: "car",
      image: "/images/car2.jpg",
      title: "SUV",
      brand: "Honda",
      model: "CR-V",
      transmission: "Automatic",
      fuelType: "Diesel",
      price: 30000,
      rentPrice: 30,
      registration: "XY456ZT",
      pickupDate: "2024-09-28",
      returnDate: "2024-10-05",
      status: "Not Available",
      description: "A spacious SUV for family trips.",
    },
    {
      id: 3,
      type: "car",
      image: "/images/car3.jpg",
      title: "Hatchback",
      brand: "Ford",
      model: "Fiesta",
      transmission: "Manual",
      fuelType: "Gasoline",
      price: 15000,
      rentPrice: 15,
      registration: "MN789OP",
      pickupDate: "2024-10-01",
      returnDate: "2024-10-10",
      status: "Available",
      description: "A compact hatchback for easy parking.",
    },
    {
      id: 4,
      type: "car",
      image: "/images/car4.jpg",
      title: "Convertible",
      brand: "BMW",
      model: "Z4",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 50000,
      rentPrice: 50,
      registration: "CV123BW",
      pickupDate: "2024-09-27",
      returnDate: "2024-09-30",
      status: "Available",
      description: "A stylish convertible for sunny days.",
    },
    {
      id: 5,
      type: "car",
      image: "/images/car5.jpg",
      title: "Coupe",
      brand: "Audi",
      model: "A5",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 40000,
      rentPrice: 40,
      registration: "CP456AD",
      pickupDate: "2024-09-29",
      returnDate: "2024-10-02",
      status: "Not Available",
      description: "A sporty coupe for a thrilling drive.",
    },
    {
      id: 6,
      type: "car",
      image: "/images/car6.jpg",
      title: "Luxury Sedan",
      brand: "Mercedes",
      model: "E-Class",
      transmission: "Automatic",
      fuelType: "Diesel",
      price: 60000,
      rentPrice: 100,
      registration: "LS789ME",
      pickupDate: "2024-10-03",
      returnDate: "2024-10-08",
      status: "Available",
      description: "A premium sedan for luxury rides.",
    },
    {
      id: 7,
      type: "car",
      image: "/images/car7.jpg",
      title: "Compact SUV",
      brand: "Nissan",
      model: "Rogue",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 25000,
      rentPrice: 25,
      registration: "CS123NS",
      pickupDate: "2024-10-01",
      returnDate: "2024-10-07",
      status: "Not Available",
      description: "A compact SUV for urban adventures.",
    },
    {
      id: 8,
      type: "car",
      image: "/images/car8.jpg",
      title: "Electric Car",
      brand: "Tesla",
      model: "Model 3",
      transmission: "Automatic",
      fuelType: "Electric",
      price: 35000,
      rentPrice: 35,
      registration: "EC456TS",
      pickupDate: "2024-10-04",
      returnDate: "2024-10-10",
      status: "Available",
      description: "An eco-friendly electric vehicle.",
    },
    {
      id: 9,
      type: "car",
      image: "/images/car9.jpg",
      title: "Pickup Truck",
      brand: "Ford",
      model: "F-150",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 45000,
      rentPrice: 45,
      registration: "PT123FD",
      pickupDate: "2024-09-30",
      returnDate: "2024-10-05",
      status: "Available",
      description: "A powerful pickup truck for heavy loads.",
    },
    {
      id: 10,
      type: "car",
      image: "/images/car10.jpg",
      title: "Minivan",
      brand: "Chrysler",
      model: "Pacifica",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 55000,
      rentPrice: 55,
      registration: "MV456CH",
      pickupDate: "2024-10-02",
      returnDate: "2024-10-07",
      status: "Not Available",
      description: "A family-friendly minivan with spacious seating.",
    },
  ],
  bikeData: [
    {
      id: 11,
      type: "bike",
      image: "/images/bike1.jpg",
      title: "Sport Bike",
      brand: "Yamaha",
      model: "YZF-R3",
      transmission: "Manual",
      fuelType: "Gasoline",
      price: 8000,
      rentPrice: 10,
      registration: "BK123YZ",
      pickupDate: "2024-09-25",
      returnDate: "2024-09-28",
      status: "Available",
      description: "A fast sport bike for thrill-seekers.",
    },
    {
      id: 12,
      type: "bike",
      image: "/images/bike2.jpg",
      title: "Cruiser",
      brand: "Harley Davidson",
      model: "Street 750",
      transmission: "Manual",
      fuelType: "Gasoline",
      price: 12000,
      rentPrice: 12,
      registration: "CR567HD",
      pickupDate: "2024-09-26",
      returnDate: "2024-09-29",
      status: "Not Available",
      description: "A classic cruiser for long rides.",
    },
    {
      id: 13,
      type: "bike",
      image: "/images/bike3.jpg",
      title: "Dirt Bike",
      brand: "Kawasaki",
      model: "KX250",
      transmission: "Manual",
      fuelType: "Gasoline",
      price: 9000,
      rentPrice: 15,
      registration: "DB123KW",
      pickupDate: "2024-09-28",
      returnDate: "2024-10-01",
      status: "Available",
      description: "A rugged dirt bike for off-road adventures.",
    },
    {
      id: 14,
      type: "bike",
      image: "/images/bike4.jpg",
      title: "Touring Bike",
      brand: "Honda",
      model: "Gold Wing",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 18000,
      rentPrice: 18,
      registration: "TB456HD",
      pickupDate: "2024-09-29",
      returnDate: "2024-10-03",
      status: "Not Available",
      description: "A touring bike for long-distance trips.",
    },
    {
      id: 15,
      type: "bike",
      image: "/images/bike5.jpg",
      title: "Electric Bike",
      brand: "Zero Motorcycles",
      model: "SR/F",
      transmission: "Automatic",
      fuelType: "Electric",
      price: 20000,
      rentPrice: 20,
      registration: "EB789ZM",
      pickupDate: "2024-09-30",
      returnDate: "2024-10-02",
      status: "Available",
      description: "An eco-friendly electric bike.",
    },
    {
      id: 16,
      type: "bike",
      image: "/images/bike6.jpg",
      title: "Standard Bike",
      brand: "Suzuki",
      model: "GSX-S750",
      transmission: "Manual",
      fuelType: "Gasoline",
      price: 8000,
      rentPrice: 8,
      registration: "SB123SZ",
      pickupDate: "2024-09-27",
      returnDate: "2024-10-01",
      status: "Available",
      description: "A standard bike for daily commuting.",
    },
    {
      id: 17,
      type: "bike",
      image: "/images/bike7.jpg",
      title: "Adventure Bike",
      brand: "BMW",
      model: "F 850 GS",
      transmission: "Manual",
      fuelType: "Gasoline",
      price: 22000,
      rentPrice: 22,
      registration: "AB123BM",
      pickupDate: "2024-10-01",
      returnDate: "2024-10-04",
      status: "Not Available",
      description: "A bike for adventure and exploration.",
    },
    {
      id: 18,
      type: "bike",
      image: "/images/bike8.jpg",
      title: "Mountain Bike",
      brand: "Giant",
      model: "Anthem",
      transmission: "Manual",
      fuelType: "Electric",
      price: 16000,
      rentPrice: 16,
      registration: "MB456GT",
      pickupDate: "2024-10-02",
      returnDate: "2024-10-05",
      status: "Available",
      description: "A mountain bike for tough terrains.",
    },
    {
      id: 19,
      type: "bike",
      image: "/images/bike9.jpg",
      title: "Scooter",
      brand: "Vespa",
      model: "GTS 300",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 5000,
      rentPrice: 5,
      registration: "SC123VP",
      pickupDate: "2024-09-30",
      returnDate: "2024-10-02",
      status: "Available",
      description: "A small and convenient scooter.",
    },
    {
      id: 20,
      type: "bike",
      image: "/images/bike10.jpg",
      title: "Moped",
      brand: "Honda",
      model: "Metropolitan",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 7000,
      rentPrice: 7,
      registration: "MP456HD",
      pickupDate: "2024-10-01",
      returnDate: "2024-10-04",
      status: "Not Available",
      description: "A lightweight moped for easy rides.",
    },
  ],
  sixSeaterData: [
    {
      id: 21,
      type: "six-seater",
      image: "/images/sixseater1.jpg",
      title: "Van",
      brand: "Toyota",
      model: "Sienna",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 40000,
      rentPrice: 40,
      registration: "SS123TO",
      pickupDate: "2024-09-25",
      returnDate: "2024-09-30",
      status: "Available",
      description: "A spacious van for group travel.",
    },
    {
      id: 22,
      type: "six-seater",
      image: "/images/sixseater2.jpg",
      title: "SUV",
      brand: "Chevrolet",
      model: "Suburban",
      transmission: "Automatic",
      fuelType: "Diesel",
      price: 50000,
      rentPrice: 50,
      registration: "SS456CH",
      pickupDate: "2024-09-26",
      returnDate: "2024-10-01",
      status: "Not Available",
      description: "An SUV with extra seating for large families.",
    },
    {
      id: 23,
      type: "six-seater",
      image: "/images/sixseater3.jpg",
      title: "Minivan",
      brand: "Honda",
      model: "Odyssey",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 45000,
      rentPrice: 45,
      registration: "SS789HO",
      pickupDate: "2024-09-27",
      returnDate: "2024-09-29",
      status: "Available",
      description: "A family-friendly minivan for long trips.",
    },
    {
      id: 24,
      type: "six-seater",
      image: "/images/sixseater4.jpg",
      title: "SUV",
      brand: "Ford",
      model: "Explorer",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 48000,
      rentPrice: 48,
      registration: "SS123FR",
      pickupDate: "2024-09-30",
      returnDate: "2024-10-04",
      status: "Not Available",
      description: "A versatile SUV with ample seating capacity.",
    },
    {
      id: 25,
      type: "six-seater",
      image: "/images/sixseater5.jpg",
      title: "Luxury SUV",
      brand: "Lexus",
      model: "LX 570",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 90000,
      rentPrice: 90,
      registration: "SS456LX",
      pickupDate: "2024-10-01",
      returnDate: "2024-10-05",
      status: "Available",
      description: "A luxury SUV for those seeking a premium experience.",
    },
    {
      id: 26,
      type: "six-seater",
      image: "/images/sixseater6.jpg",
      title: "Electric SUV",
      brand: "Tesla",
      model: "Model X",
      transmission: "Automatic",
      fuelType: "Electric",
      price: 120000,
      rentPrice: 100,
      registration: "SS789TS",
      pickupDate: "2024-09-28",
      returnDate: "2024-10-03",
      status: "Not Available",
      description: "An eco-friendly electric SUV with futuristic features.",
    },
    {
      id: 27,
      type: "six-seater",
      image: "/images/sixseater7.jpg",
      title: "Van",
      brand: "Mercedes-Benz",
      model: "Metris",
      transmission: "Automatic",
      fuelType: "Diesel",
      price: 60000,
      rentPrice: 55,
      registration: "SS123MB",
      pickupDate: "2024-10-02",
      returnDate: "2024-10-07",
      status: "Available",
      description: "A premium van perfect for small business transportation.",
    },
    {
      id: 28,
      type: "six-seater",
      image: "/images/sixseater8.jpg",
      title: "Minivan",
      brand: "Kia",
      model: "Carnival",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 35000,
      rentPrice: 35,
      registration: "SS456KI",
      pickupDate: "2024-09-29",
      returnDate: "2024-10-03",
      status: "Available",
      description: "A well-rounded minivan for family road trips.",
    },
    {
      id: 29,
      type: "six-seater",
      image: "/images/sixseater9.jpg",
      title: "SUV",
      brand: "Nissan",
      model: "Armada",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 55000,
      rentPrice: 52,
      registration: "SS789NI",
      pickupDate: "2024-10-01",
      returnDate: "2024-10-05",
      status: "Not Available",
      description: "A robust SUV for large families or groups.",
    },
    {
      id: 30,
      type: "six-seater",
      image: "/images/sixseater10.jpg",
      title: "Crossover",
      brand: "Hyundai",
      model: "Palisade",
      transmission: "Automatic",
      fuelType: "Gasoline",
      price: 45000,
      rentPrice: 42,
      registration: "SS456HY",
      pickupDate: "2024-10-03",
      returnDate: "2024-10-06",
      status: "Available",
      description: "A feature-packed crossover with spacious seating.",
    },
  ],
};
